# Generated by Django 2.0.5 on 2018-06-30 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello_uptime', '0002_auto_20180519_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='url',
            new_name='monitor_url',
        ),
        migrations.AlterUniqueTogether(
            name='monitor',
            unique_together={('user', 'monitor_url')},
        ),
    ]
