version: '3'

services:
  web:
    build: .
  celery:
    build: .
    command: celery worker -l info -A hello_django
    depends_on:
      - amqp
  celery-beat:
    build: .
    command: celery beat -l info -A hello_django --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - amqp
      - celery
  amqp:
    image: rabbitmq:3.7
