version: '3'

services:
  web:
    command: python manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
  test-web1:
    image: nginx:alpine
    ports:
      - 8001:80
  test-web2:
    image: nginx:alpine
    ports:
      - 8002:80
