# Generated by Django 2.0.3 on 2018-04-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_palette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted?'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='colors',
            field=models.TextField(editable=False, verbose_name='Colors'),
        ),
    ]
