# Generated by Django 2.0.5 on 2018-05-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('interval', models.PositiveSmallIntegerField(choices=[(300, '5 minutes'), (1800, 'Half an hour'), (3600, '1 hour'), (21600, '6 hours')], default=1800, verbose_name='Monitoring interval')),
                ('status', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=9, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('checked_at', models.DateTimeField(editable=False, null=True, verbose_name='Checked at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitors',
                'ordering': ('-created_at',),
            },
        ),
    ]
